---
- hosts: all
  become: true
  tasks:
  - name: update apt
    apt: 
      update_cache: yes
  - name: install openjdk
    apt:
      name: openjdk-8-jdk
      state: present
  - name: import jenkins key
    apt_key:
      state: present
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
  - name: download jenkins.repo
    apt_repository:
     repo: deb https://pkg.jenkins.io/debian-stable binary/
     state: present 
  - name: install jenkins
    apt:
      name: jenkins
      state: present

  - name: start jenkins
    systemd:
      name: jenkins
      state: started

  - name: enable jenkins
    systemd:
      name: jenkins
      enabled: true

  - name: sleep for 30 seconds and continue with play
    wait_for: timeout=30
    delegate_to: localhost

  - name: init password jenkin
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result

  - name: print init password jenkins
    debug:
      var: result.stdout

