---
- hosts: all
  become: yes
  tasks:
  - name: Update apt
    apt:
     update_cache: yes
     upgrade: yes
  - name: Install base packages
    apt: name={{ item }} state=present
    with_items:
      - locales
      - build-essential
      - acl
      - ntp
      - htop
      - git
      - mocha
      - supervisor
      - python-pip
      - python3-pip
      - nginx
      - nodejs
    tags:
      - packages
  - name: Upgrade pip
    pip: name=pip state=latest
    tags:
      - packages
  - name: Create user
    user:
      name: "deploy_user"
      comment: "Used to deploy Django"
      state: present
  - name: Create .ssh folder
    file:
      path: "/home/deploy_user/.ssh/"
      state: directory
      mode: 0755